"""Generates the datasource/cache properties appended to application.properties."""

from __future__ import annotations

from pathlib import Path

from ..config import ProjectConfig

# (host, port) used consistently across application.properties and docker-compose.yml
DB_DEFAULTS = {
    "postgresql": {"port": 5432, "user": "postgres", "password": "postgres"},
    "mysql": {"port": 3306, "user": "root", "password": "root"},
    "mongodb": {"port": 27017, "user": None, "password": None},
    "h2": {"port": None, "user": "sa", "password": ""},
}
REDIS_DEFAULTS = {"port": 6379}


def _db_properties(config: ProjectConfig) -> list[str]:
    db = config.database
    name = config.artifact_id
    lines: list[str] = []

    if db == "postgresql":
        if config.reactive:
            lines += [
                f"spring.r2dbc.url=r2dbc:postgresql://localhost:5432/{name}",
                "spring.r2dbc.username=postgres",
                "spring.r2dbc.password=postgres",
            ]
        else:
            lines += [
                f"spring.datasource.url=jdbc:postgresql://localhost:5432/{name}",
                "spring.datasource.username=postgres",
                "spring.datasource.password=postgres",
                "spring.jpa.hibernate.ddl-auto=update",
                "spring.jpa.open-in-view=false",
            ]
    elif db == "mysql":
        if config.reactive:
            lines += [
                f"spring.r2dbc.url=r2dbc:mysql://localhost:3306/{name}",
                "spring.r2dbc.username=root",
                "spring.r2dbc.password=root",
            ]
        else:
            lines += [
                f"spring.datasource.url=jdbc:mysql://localhost:3306/{name}?useSSL=false&allowPublicKeyRetrieval=true",
                "spring.datasource.username=root",
                "spring.datasource.password=root",
                "spring.jpa.hibernate.ddl-auto=update",
                "spring.jpa.open-in-view=false",
            ]
    elif db == "h2":
        if config.reactive:
            lines += [f"spring.r2dbc.url=r2dbc:h2:mem:///{name};DB_CLOSE_DELAY=-1"]
        else:
            lines += [
                f"spring.datasource.url=jdbc:h2:mem:{name};DB_CLOSE_DELAY=-1",
                "spring.datasource.username=sa",
                "spring.datasource.password=",
                "spring.jpa.hibernate.ddl-auto=update",
                "spring.h2.console.enabled=true",
            ]
    elif db == "mongodb":
        lines += [f"spring.data.mongodb.uri=mongodb://localhost:27017/{name}"]

    return lines


def _cache_properties(config: ProjectConfig) -> list[str]:
    if config.caching == "redis":
        return [
            "spring.cache.type=redis",
            "spring.data.redis.host=localhost",
            "spring.data.redis.port=6379",
        ]
    if config.caching == "caffeine":
        return [
            "spring.cache.type=caffeine",
            "spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=600s",
        ]
    return []


def apply(config: ProjectConfig) -> None:
    """Append DB/cache configuration to application.properties."""
    lines = _db_properties(config) + _cache_properties(config)
    if not lines:
        return

    props_path = config.project_path() / "src" / "main" / "resources" / "application.properties"
    props_path.parent.mkdir(parents=True, exist_ok=True)

    header = "\n# --- generated by spring-cli ---\n"
    with props_path.open("a", encoding="utf-8") as f:
        f.write(header)
        for line in lines:
            f.write(line + "\n")
