"""Project configuration model shared across the wizard, Initializr client and feature generators."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ProjectConfig:
    # Core Initializr fields
    language: str = "java"          # java | kotlin
    build_tool: str = "maven"       # maven | gradle
    boot_version: str = ""          # e.g. "3.5.0" (blank = Initializr default)
    java_version: str = "21"
    packaging: str = "jar"          # jar | war

    group_id: str = "com.example"
    artifact_id: str = "demo"
    name: str = "demo"
    package_name: str = ""          # derived from group_id + artifact_id if blank
    description: str = "Demo project generated by spring-cli"

    # Wizard choices
    reactive: bool = False
    database: str = "none"          # postgresql | mysql | mongodb | h2 | none
    caching: str = "none"           # redis | caffeine | none
    security: bool = False
    actuator: bool = False
    lombok: bool = False
    docker: bool = False
    ci: bool = False

    output_dir: Path = field(default_factory=lambda: Path("."))

    def resolved_package_name(self) -> str:
        if self.package_name:
            return self.package_name
        return self.group_id

    def project_path(self) -> Path:
        return self.output_dir / self.artifact_id
